# Generated by Django 4.2 on 2026-02-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dataio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelfield',
            old_name='field',
            new_name='name',
        ),
    ]
